name: quiescent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - cython
  - hdf5
  - h5py
  - emcee
  - dynesty
  - gsl
  - openblas
  - openmpi
  - mpi4py
  - pip
  - pip:
    - jupyterlab
    - matplotlib
    - astropy
    - fsps
    - astro-sedpy
    - astro-prospector
    - pyneb