channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - cython
  - hdf5
  - h5py
  - emcee
  - dynesty
  - nautilus-sampler
  - gsl
  - openblas
  - openmpi
  - mpi4py
  - git
  - gfortran
  - cmake
  - ninja
  - scikit-build
  - setuptools_scm
  - pip
  - pip:
    - scikit-build-core
    - jupyterlab
    - matplotlib
    - astropy
    - astro-sedpy
    # Note: fsps is intentionally NOT listed here (built later with FFLAGS)
    # Note: prospector dev install is done from local repo in the script
    # -- extra packages
    - pandas
    - lmfit
    - numdifftools