name: scalpel-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pip
  - arviz
  - asdf
  - astropy
  - corner
  - jax
  - jaxopt
  - matplotlib
  - numpy
  - numpyro
  - pandas
  - photutils
  - sep
  - scipy
  - tqdm
  - pip:
      - equinox
      - interpax
      - pysersic
      - astro-sedpy
      - stpsf
      - reproject
      - -e /Users/Jonah/PhD/Research/quiescent_galaxies/scalpel