name: quiescent-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=2.19.0=py311hecd8cb5_0
  - aiohappyeyeballs=2.4.4=py311hecd8cb5_0
  - aiohttp=3.11.10=py311h46256e1_0
  - aioitertools=0.12.0=py311hecd8cb5_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - boto3=1.36.3=py311hecd8cb5_0
  - botocore=1.36.3=py311hecd8cb5_0
  - brotli=1.1.0=h1c43f85_4
  - brotli-bin=1.1.0=h1c43f85_4
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cctools=1024.3=h8f84d09_4
  - cctools_osx-64=1024.3=h70b0a0a_4
  - clang=20.1.8=default_h1323312_3
  - clang-20=20.1.8=default_hc369343_3
  - clang_impl_osx-64=20.1.8=h1545fa4_25
  - clang_osx-64=20.1.8=h7e5c614_25
  - compiler-rt=20.1.8=he914875_1
  - compiler-rt_osx-64=20.1.8=h138dee1_1
  - contourpy=1.3.3=py311hd4d69bb_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cython=3.1.4=py311h8726017_2
  - dynesty=2.1.5=pyhd8ed1ab_0
  - emcee=3.1.6=pyhd8ed1ab_1
  - fonttools=4.60.1=py311he13f9b5_0
  - freetype=2.14.1=h694c41f_0
  - frozenlist=1.5.0=py311h46256e1_0
  - fsspec=2025.7.0=py311he13d532_0
  - gfortran=15.1.0=hcc3c99d_0
  - gfortran_impl_osx-64=15.1.0=h38112e1_1
  - gfortran_osx-64=15.1.0=h3223c34_0
  - git=2.51.0=pl5321h110a47f_1
  - gmp=6.3.0=hf036a51_2
  - gsl=2.8=hc707ee6_1
  - h5py=3.14.0=nompi_py311h9f650d9_101
  - hdf5=1.14.6=nompi_hc8237f9_103
  - isl=0.26=imath32_h2e86a7b_101
  - jmespath=1.0.1=py311hecd8cb5_0
  - kiwisolver=1.4.9=py311ha94bed4_1
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - ld64=955.13=h2b71b23_4
  - ld64_osx-64=955.13=h21bdf93_4
  - lerc=4.0.0=hcca01a6_1
  - libaec=1.1.4=ha6bc127_0
  - libblas=3.9.0=36_he492b99_openblas
  - libbrotlicommon=1.1.0=h1c43f85_4
  - libbrotlidec=1.1.0=h1c43f85_4
  - libbrotlienc=1.1.0=h1c43f85_4
  - libcblas=3.9.0=36_h9b27e0a_openblas
  - libclang-cpp20.1=20.1.8=default_hc369343_3
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=21.1.2=h3d58e20_0
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.1=h21dd04a_0
  - libfabric=2.2.0=h694c41f_2
  - libfabric1=2.2.0=h1c43f85_2
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgfortran=15.1.0=h5f6db21_1
  - libgfortran-devel_osx-64=15.1.0=h5f6db21_1
  - libgfortran5=15.1.0=hfa3c126_1
  - libhwloc=2.12.1=default_h094e1f9_1002
  - libiconv=1.18=h57a12c2_2
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=36_h859234e_openblas
  - libllvm20=20.1.8=h56e7563_1
  - liblzma=5.8.1=hd471939_2
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h83c2472_2
  - libpmix=5.0.8=h7a6afba_2
  - libpng=1.6.50=h84aeda2_1
  - libsqlite=3.50.4=h39a8b3b_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.1=haa3b502_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.15.0=h23bb396_1
  - libxml2-16=2.15.0=h0ad03eb_1
  - libzlib=1.3.1=hd23fc13_2
  - llvm-openmp=21.1.2=h472b3d1_1
  - llvm-tools=20.1.8=hb0207f0_1
  - llvm-tools-20=20.1.8=h879f4bc_1
  - matplotlib-base=3.10.6=py311h48d7e91_1
  - mpc=1.3.1=h9d8efa1_1
  - mpfr=4.2.1=haed47dc_3
  - mpi=1.0.1=openmpi
  - mpi4py=4.1.0=py311h2196963_103
  - multidict=6.1.0=py311h46256e1_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h0622a9a_3
  - openblas=0.3.30=openmp_h30af337_2
  - openjpeg=2.5.4=h87e8dc5_0
  - openmpi=5.0.8=h0c582a8_108
  - openssl=3.5.3=h230baf5_1
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.46=ha3e7e28_0
  - perl=5.32.1=7_h10d778d_perl5
  - pip=25.2=pyh8b19718_0
  - propcache=0.3.1=py311h46256e1_0
  - pthread-stubs=0.4=h00291cd_1002
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=h9ccd52b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - s3fs=2025.7.0=py311hecd8cb5_0
  - s3transfer=0.11.2=py311hecd8cb5_0
  - scipy=1.16.2=py311h32c7e5c_0
  - setuptools=80.9.0=pyhff2d567_0
  - sigtool=0.1.3=h88f4db0_0
  - six=1.17.0=pyhe01879c_1
  - tapi=1300.6.5=h390ca13_0
  - tk=8.6.13=hf689a15_2
  - unicodedata2=16.0.0=py311h13e5629_1
  - urllib3=2.5.0=py311hecd8cb5_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py311h46256e1_0
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - yarl=1.18.0=py311h46256e1_0
  - zlib=1.3.1=hd23fc13_2
  - zstd=1.5.7=h8210216_2
  - pip:
    - anyio==4.11.0
    - appnope==0.1.4
    - argon2-cffi==25.1.0
    - argon2-cffi-bindings==25.1.0
    - arrow==1.3.0
    - asdf==3.5.0
    - asdf-astropy==0.8.0
    - asdf-coordinates-schemas==0.4.0
    - asdf-standard==1.4.0
    - asdf-transform-schemas==0.6.0
    - asdf-wcs-schemas==0.5.0
    # - astro-prospector==2.0a2.dev42+gff8d5e4d5
    - -e /Users/Jonah/PhD/Research/quiescent_galaxies/dev/prospector_v2
    - astro-sedpy==0.4.1
    - astrocut==0.9
    - astropy==7.1.0
    - astropy-iers-data==0.2025.9.29.0.35.48
    - astroquery==0.4.11
    - asttokens==3.0.0
    - async-lru==2.0.5
    - attrs==25.3.0
    - babel==2.17.0
    - backports-tarfile==1.2.0
    - bayesicfitting==3.2.4
    - beautifulsoup4==4.14.2
    - bleach==6.2.0
    - blinker==1.9.0
    - blosc2==3.9.1
    - bokeh==3.8.0
    - certifi==2025.8.3
    - cffi==2.0.0
    - charset-normalizer==3.4.3
    - click==8.3.0
    - comm==0.2.3
    - corner==2.2.3
    - crds==13.0.6
    - debugpy==1.8.17
    - decorator==5.2.1
    - defusedxml==0.7.1
    - drizzle==2.1.1
    - drizzlepac==3.6.2
    - dust-extinction==1.6
    - eazy==0.8.5
    - et-xmlfile==2.0.0
    - executing==2.2.1
    - extinction==0.4.8
    - fastjsonschema==2.21.2
    - filelock==3.19.1
    - fitsblender==0.4.4
    - flask==2.1.3
    - fqdn==1.5.1
    - fsps==0.4.7
    - future==1.0.0
    - geos==0.2.3
    - grismconf==1.32
    - grizli==1.13.1
    - gwcs==0.22.1
    - h11==0.16.0
    - html5lib==1.1
    - httpcore==1.0.9
    - httpx==0.28.1
    - idna==3.10
    - imageio==2.37.0
    - importlib-metadata==8.7.0
    - ipykernel==6.30.1
    - ipython==9.6.0
    - ipython-pygments-lexers==1.1.1
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.5.2
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.9.1
    - jupyter-client==8.6.3
    - jupyter-core==5.8.1
    - jupyter-events==0.12.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.17.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.4.9
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jwst==1.16.1
    - keyring==25.6.0
    - lark==1.3.0
    - lazy-loader==0.4
    - llvmlite==0.45.1
    - lxml==6.0.2
    - markupsafe==2.0.1
    - mastquery==1.8.5
    - matplotlib-inline==0.1.7
    - mistune==3.1.4
    - more-itertools==10.8.0
    - msaexp==0.9.11
    - msgpack==1.1.1
    - narwhals==2.7.0
    - nautilus-sampler==1.0.5
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - ndindex==1.10.0
    - nest-asyncio==1.6.0
    - networkx==3.5
    - notebook-shim==0.2.4
    - numba==0.62.1
    - numexpr==2.13.1
    - numpy==1.26.4
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - overrides==7.7.0
    - pandas==2.3.3
    - pandocfilters==1.5.1
    - parsley==1.3
    - parso==0.8.5
    - peakutils==1.3.5
    - pexpect==4.9.0
    - photutils==1.12.0
    - pillow==11.2.1
    - platformdirs==4.4.0
    - poppy==1.1.2
    - prometheus-client==0.23.1
    - prompt-toolkit==3.0.52
    - psutil==7.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - pycparser==2.23
    - pyerfa==2.0.1.5
    - pygments==2.19.2
    - pypdf2==3.0.1
    - pysiaf==0.24.1
    - python-json-logger==3.3.0
    - pytz==2025.2
    - pyvo==1.7
    - pyyaml==6.0.3
    - pyzmq==27.1.0
    - referencing==0.36.2
    - regions==0.10
    - requests==2.32.5
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rfc3987-syntax==1.1.0
    - rpds-py==0.27.1
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - semantic-version==2.10.0
    - send2trash==1.8.3
    - sep==1.4.1
    - shapely==2.1.2
    - sniffio==1.3.1
    - snowblind==0.2.1
    - soupsieve==2.8
    - spherical-geometry==1.3.3
    - sregion==1.6
    - stack-data==0.6.3
    - stcal==1.9.0
    - stdatamodels==2.1.2
    - stpipe==0.7.0
    - stregion==1.1.10
    - stsci-image==2.3.11
    - stsci-imagestats==1.8.3
    - stsci-skypac==1.0.11
    - stsci-stimage==0.3.0
    - stsci-tools==4.2.0
    - stwcs==1.7.3
    - synphot==1.6.0
    - tables==3.10.2
    - terminado==0.18.1
    - threadpoolctl==3.6.0
    - tifffile==2025.10.4
    - tinycss2==1.4.0
    - tornado==6.5.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - tristars==0.1
    - tweakwcs==0.8.11
    - types-python-dateutil==2.9.0.20250822
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - uri-template==1.3.0
    - wcwidth==0.2.14
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==2.1.2
    - wiimatch==0.3.2
    - xyzservices==2025.4.0
    - zipp==3.23.0
prefix: /Users/Jonah/opt/anaconda3/envs/quiescent-dev
